version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password

    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  backend:
    container_name: django_social_ranking
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["sh", "-c", "python manage.py migrate && python manage.py runserver"]
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data:
