version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql_rec_eng
    restart: always

    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    expose:
      - "3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
          "-e",
          "SELECT 1",
        ]
      timeout: 20s
      retries: 10

  backend:
    container_name: django_social_ranking
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py makemigrations && 
             python3 manage.py migrate --noinput &&
             python3 manage.py import_data suburbs_10.xlsx &&
             python3 manage.py collectstatic --noinput --ignore static &&
             gunicorn ranking_social.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend
volumes:
  data:
  static_volume:
