# Generated by Django 5.0.4 on 2024-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('countlike', models.IntegerField()),
                ('countComment', models.IntegerField()),
                ('countShare', models.IntegerField()),
            ],
        ),
    ]
