# Generated by Django 5.0.4 on 2024-05-20 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='addressShortAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='suburb_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countComment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countLike',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countShare',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countView',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='suburbs',
            name='Good_Schools',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='suburbs',
            name='Postcode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
        migrations.AlterField(
            model_name='suburbs',
            name='SAL',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative.')]),
        ),
    ]
