# Generated by Django 5.0.4 on 2024-04-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='countlike',
            new_name='countLike',
        ),
    ]
