# Generated by Django 5.0.4 on 2024-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_countlike_posts_countlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
