# Generated by Django 5.0.4 on 2024-04-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts_createdat_posts_updatedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='ranking',
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_ranking', models.IntegerField(default=0)),
                ('weekly_ranking', models.IntegerField(default=0)),
                ('sum_ranking', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
            ],
        ),
    ]
