# Generated by Django 5.0.4 on 2024-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_posts_ranking_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(default=1)),
                ('like', models.IntegerField(default=5)),
                ('comment', models.IntegerField(default=10)),
                ('share', models.IntegerField(default=20)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='countView',
            field=models.IntegerField(default=0),
        ),
    ]
