# Generated by Django 5.0.4 on 2024-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_point_posts_countview'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='postCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='yesterday_sum_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
