# Generated by Django 5.0.4 on 2024-04-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_posts_location_posts_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
