# Generated by Django 5.0.4 on 2024-04-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.TextField(unique=True),
        ),
    ]
