# Generated by Django 5.0.4 on 2024-04-22 02:56

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_posts_location_alter_posts_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_suburb', models.IntegerField(default=0)),
                ('Suburb', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=10)),
                ('PostCode', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')])),
                ('Combined', models.TextField(max_length=100)),
                ('Latitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('CBD', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('is_old', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')])),
                ('len', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='countComment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countLike',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countShare',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='countView',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postCode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.TextField(max_length=255, unique=True, validators=[api.models.validate_with_spectial_charactor]),
        ),
    ]
