# Generated by Django 5.0.4 on 2024-04-24 02:26

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_len_suburbs_len_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='suburbs',
            field=models.ForeignKey(default=api.models.get_default_suburb, on_delete=django.db.models.deletion.CASCADE, to='api.suburbs'),
        ),
        migrations.AddField(
            model_name='suburbs',
            name='Nearby',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suburbs',
            name='Nearby_Dis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suburbs',
            name='Nearby_Dis_List',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suburbs',
            name='Nearby_List',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suburbs',
            name='Nearby_List_Codes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suburbs',
            name='id_suburb',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be non-negative')]),
        ),
    ]
