# Generated by Django 5.0.4 on 2024-04-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_posts_suburbs_suburbs_nearby_suburbs_nearby_dis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='location',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='postCode',
        ),
    ]
