# Generated by Django 5.0.4 on 2024-04-26 04:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_posts_location_remove_posts_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.CharField(max_length=255, unique=True, validators=[api.models.validate_with_spectial_charactor]),
        ),
    ]
